// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/uzapi/ent/activationcode"
	"github.com/uzapi/ent/predicate"
	"github.com/uzapi/ent/user"
)

// ActivationCodeUpdate is the builder for updating ActivationCode entities.
type ActivationCodeUpdate struct {
	config
	hooks    []Hook
	mutation *ActivationCodeMutation
}

// Where appends a list predicates to the ActivationCodeUpdate builder.
func (_u *ActivationCodeUpdate) Where(ps ...predicate.ActivationCode) *ActivationCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *ActivationCodeUpdate) SetCode(v string) *ActivationCodeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ActivationCodeUpdate) SetNillableCode(v *string) *ActivationCodeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ActivationCodeUpdate) SetAmount(v float64) *ActivationCodeUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ActivationCodeUpdate) SetNillableAmount(v *float64) *ActivationCodeUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ActivationCodeUpdate) AddAmount(v float64) *ActivationCodeUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ActivationCodeUpdate) SetStatus(v string) *ActivationCodeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ActivationCodeUpdate) SetNillableStatus(v *string) *ActivationCodeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *ActivationCodeUpdate) SetStartsAt(v time.Time) *ActivationCodeUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *ActivationCodeUpdate) SetNillableStartsAt(v *time.Time) *ActivationCodeUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (_u *ActivationCodeUpdate) ClearStartsAt() *ActivationCodeUpdate {
	_u.mutation.ClearStartsAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ActivationCodeUpdate) SetExpiresAt(v time.Time) *ActivationCodeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ActivationCodeUpdate) SetNillableExpiresAt(v *time.Time) *ActivationCodeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ActivationCodeUpdate) ClearExpiresAt() *ActivationCodeUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUsedBy sets the "used_by" field.
func (_u *ActivationCodeUpdate) SetUsedBy(v int64) *ActivationCodeUpdate {
	_u.mutation.SetUsedBy(v)
	return _u
}

// SetNillableUsedBy sets the "used_by" field if the given value is not nil.
func (_u *ActivationCodeUpdate) SetNillableUsedBy(v *int64) *ActivationCodeUpdate {
	if v != nil {
		_u.SetUsedBy(*v)
	}
	return _u
}

// ClearUsedBy clears the value of the "used_by" field.
func (_u *ActivationCodeUpdate) ClearUsedBy() *ActivationCodeUpdate {
	_u.mutation.ClearUsedBy()
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *ActivationCodeUpdate) SetUsedAt(v time.Time) *ActivationCodeUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *ActivationCodeUpdate) SetNillableUsedAt(v *time.Time) *ActivationCodeUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *ActivationCodeUpdate) ClearUsedAt() *ActivationCodeUpdate {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ActivationCodeUpdate) SetNotes(v string) *ActivationCodeUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ActivationCodeUpdate) SetNillableNotes(v *string) *ActivationCodeUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ActivationCodeUpdate) ClearNotes() *ActivationCodeUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ActivationCodeUpdate) SetUpdatedAt(v time.Time) *ActivationCodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ActivationCodeUpdate) SetUserID(id int64) *ActivationCodeUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *ActivationCodeUpdate) SetNillableUserID(id *int64) *ActivationCodeUpdate {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ActivationCodeUpdate) SetUser(v *User) *ActivationCodeUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ActivationCodeMutation object of the builder.
func (_u *ActivationCodeUpdate) Mutation() *ActivationCodeMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ActivationCodeUpdate) ClearUser() *ActivationCodeUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ActivationCodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActivationCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ActivationCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActivationCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ActivationCodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := activationcode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActivationCodeUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := activationcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ActivationCode.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := activationcode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ActivationCode.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ActivationCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activationcode.Table, activationcode.Columns, sqlgraph.NewFieldSpec(activationcode.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(activationcode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(activationcode.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(activationcode.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(activationcode.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(activationcode.FieldStartsAt, field.TypeTime, value)
	}
	if _u.mutation.StartsAtCleared() {
		_spec.ClearField(activationcode.FieldStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(activationcode.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(activationcode.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(activationcode.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(activationcode.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(activationcode.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(activationcode.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(activationcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activationcode.UserTable,
			Columns: []string{activationcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activationcode.UserTable,
			Columns: []string{activationcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ActivationCodeUpdateOne is the builder for updating a single ActivationCode entity.
type ActivationCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ActivationCodeMutation
}

// SetCode sets the "code" field.
func (_u *ActivationCodeUpdateOne) SetCode(v string) *ActivationCodeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ActivationCodeUpdateOne) SetNillableCode(v *string) *ActivationCodeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ActivationCodeUpdateOne) SetAmount(v float64) *ActivationCodeUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ActivationCodeUpdateOne) SetNillableAmount(v *float64) *ActivationCodeUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ActivationCodeUpdateOne) AddAmount(v float64) *ActivationCodeUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ActivationCodeUpdateOne) SetStatus(v string) *ActivationCodeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ActivationCodeUpdateOne) SetNillableStatus(v *string) *ActivationCodeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *ActivationCodeUpdateOne) SetStartsAt(v time.Time) *ActivationCodeUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *ActivationCodeUpdateOne) SetNillableStartsAt(v *time.Time) *ActivationCodeUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (_u *ActivationCodeUpdateOne) ClearStartsAt() *ActivationCodeUpdateOne {
	_u.mutation.ClearStartsAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ActivationCodeUpdateOne) SetExpiresAt(v time.Time) *ActivationCodeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ActivationCodeUpdateOne) SetNillableExpiresAt(v *time.Time) *ActivationCodeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ActivationCodeUpdateOne) ClearExpiresAt() *ActivationCodeUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUsedBy sets the "used_by" field.
func (_u *ActivationCodeUpdateOne) SetUsedBy(v int64) *ActivationCodeUpdateOne {
	_u.mutation.SetUsedBy(v)
	return _u
}

// SetNillableUsedBy sets the "used_by" field if the given value is not nil.
func (_u *ActivationCodeUpdateOne) SetNillableUsedBy(v *int64) *ActivationCodeUpdateOne {
	if v != nil {
		_u.SetUsedBy(*v)
	}
	return _u
}

// ClearUsedBy clears the value of the "used_by" field.
func (_u *ActivationCodeUpdateOne) ClearUsedBy() *ActivationCodeUpdateOne {
	_u.mutation.ClearUsedBy()
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *ActivationCodeUpdateOne) SetUsedAt(v time.Time) *ActivationCodeUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *ActivationCodeUpdateOne) SetNillableUsedAt(v *time.Time) *ActivationCodeUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *ActivationCodeUpdateOne) ClearUsedAt() *ActivationCodeUpdateOne {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ActivationCodeUpdateOne) SetNotes(v string) *ActivationCodeUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ActivationCodeUpdateOne) SetNillableNotes(v *string) *ActivationCodeUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ActivationCodeUpdateOne) ClearNotes() *ActivationCodeUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ActivationCodeUpdateOne) SetUpdatedAt(v time.Time) *ActivationCodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ActivationCodeUpdateOne) SetUserID(id int64) *ActivationCodeUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *ActivationCodeUpdateOne) SetNillableUserID(id *int64) *ActivationCodeUpdateOne {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ActivationCodeUpdateOne) SetUser(v *User) *ActivationCodeUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ActivationCodeMutation object of the builder.
func (_u *ActivationCodeUpdateOne) Mutation() *ActivationCodeMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ActivationCodeUpdateOne) ClearUser() *ActivationCodeUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ActivationCodeUpdate builder.
func (_u *ActivationCodeUpdateOne) Where(ps ...predicate.ActivationCode) *ActivationCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ActivationCodeUpdateOne) Select(field string, fields ...string) *ActivationCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ActivationCode entity.
func (_u *ActivationCodeUpdateOne) Save(ctx context.Context) (*ActivationCode, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActivationCodeUpdateOne) SaveX(ctx context.Context) *ActivationCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ActivationCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActivationCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ActivationCodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := activationcode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActivationCodeUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := activationcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ActivationCode.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := activationcode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ActivationCode.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ActivationCodeUpdateOne) sqlSave(ctx context.Context) (_node *ActivationCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activationcode.Table, activationcode.Columns, sqlgraph.NewFieldSpec(activationcode.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ActivationCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, activationcode.FieldID)
		for _, f := range fields {
			if !activationcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != activationcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(activationcode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(activationcode.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(activationcode.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(activationcode.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(activationcode.FieldStartsAt, field.TypeTime, value)
	}
	if _u.mutation.StartsAtCleared() {
		_spec.ClearField(activationcode.FieldStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(activationcode.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(activationcode.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(activationcode.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(activationcode.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(activationcode.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(activationcode.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(activationcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activationcode.UserTable,
			Columns: []string{activationcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activationcode.UserTable,
			Columns: []string{activationcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ActivationCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
