// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/uzapi/ent/activationcode"
	"github.com/uzapi/ent/user"
)

// ActivationCodeCreate is the builder for creating a ActivationCode entity.
type ActivationCodeCreate struct {
	config
	mutation *ActivationCodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCode sets the "code" field.
func (_c *ActivationCodeCreate) SetCode(v string) *ActivationCodeCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *ActivationCodeCreate) SetAmount(v float64) *ActivationCodeCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *ActivationCodeCreate) SetNillableAmount(v *float64) *ActivationCodeCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ActivationCodeCreate) SetStatus(v string) *ActivationCodeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ActivationCodeCreate) SetNillableStatus(v *string) *ActivationCodeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *ActivationCodeCreate) SetStartsAt(v time.Time) *ActivationCodeCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_c *ActivationCodeCreate) SetNillableStartsAt(v *time.Time) *ActivationCodeCreate {
	if v != nil {
		_c.SetStartsAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ActivationCodeCreate) SetExpiresAt(v time.Time) *ActivationCodeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ActivationCodeCreate) SetNillableExpiresAt(v *time.Time) *ActivationCodeCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetUsedBy sets the "used_by" field.
func (_c *ActivationCodeCreate) SetUsedBy(v int64) *ActivationCodeCreate {
	_c.mutation.SetUsedBy(v)
	return _c
}

// SetNillableUsedBy sets the "used_by" field if the given value is not nil.
func (_c *ActivationCodeCreate) SetNillableUsedBy(v *int64) *ActivationCodeCreate {
	if v != nil {
		_c.SetUsedBy(*v)
	}
	return _c
}

// SetUsedAt sets the "used_at" field.
func (_c *ActivationCodeCreate) SetUsedAt(v time.Time) *ActivationCodeCreate {
	_c.mutation.SetUsedAt(v)
	return _c
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_c *ActivationCodeCreate) SetNillableUsedAt(v *time.Time) *ActivationCodeCreate {
	if v != nil {
		_c.SetUsedAt(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *ActivationCodeCreate) SetNotes(v string) *ActivationCodeCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *ActivationCodeCreate) SetNillableNotes(v *string) *ActivationCodeCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ActivationCodeCreate) SetCreatedAt(v time.Time) *ActivationCodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ActivationCodeCreate) SetNillableCreatedAt(v *time.Time) *ActivationCodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ActivationCodeCreate) SetUpdatedAt(v time.Time) *ActivationCodeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ActivationCodeCreate) SetNillableUpdatedAt(v *time.Time) *ActivationCodeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *ActivationCodeCreate) SetUserID(id int64) *ActivationCodeCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_c *ActivationCodeCreate) SetNillableUserID(id *int64) *ActivationCodeCreate {
	if id != nil {
		_c = _c.SetUserID(*id)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ActivationCodeCreate) SetUser(v *User) *ActivationCodeCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ActivationCodeMutation object of the builder.
func (_c *ActivationCodeCreate) Mutation() *ActivationCodeMutation {
	return _c.mutation
}

// Save creates the ActivationCode in the database.
func (_c *ActivationCodeCreate) Save(ctx context.Context) (*ActivationCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ActivationCodeCreate) SaveX(ctx context.Context) *ActivationCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActivationCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActivationCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ActivationCodeCreate) defaults() {
	if _, ok := _c.mutation.Amount(); !ok {
		v := activationcode.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := activationcode.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := activationcode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := activationcode.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ActivationCodeCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "ActivationCode.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := activationcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ActivationCode.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "ActivationCode.amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ActivationCode.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := activationcode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ActivationCode.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ActivationCode.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ActivationCode.updated_at"`)}
	}
	return nil
}

func (_c *ActivationCodeCreate) sqlSave(ctx context.Context) (*ActivationCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ActivationCodeCreate) createSpec() (*ActivationCode, *sqlgraph.CreateSpec) {
	var (
		_node = &ActivationCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(activationcode.Table, sqlgraph.NewFieldSpec(activationcode.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(activationcode.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(activationcode.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(activationcode.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(activationcode.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(activationcode.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.UsedAt(); ok {
		_spec.SetField(activationcode.FieldUsedAt, field.TypeTime, value)
		_node.UsedAt = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(activationcode.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(activationcode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(activationcode.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activationcode.UserTable,
			Columns: []string{activationcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UsedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ActivationCode.Create().
//		SetCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ActivationCodeUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *ActivationCodeCreate) OnConflict(opts ...sql.ConflictOption) *ActivationCodeUpsertOne {
	_c.conflict = opts
	return &ActivationCodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ActivationCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ActivationCodeCreate) OnConflictColumns(columns ...string) *ActivationCodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ActivationCodeUpsertOne{
		create: _c,
	}
}

type (
	// ActivationCodeUpsertOne is the builder for "upsert"-ing
	//  one ActivationCode node.
	ActivationCodeUpsertOne struct {
		create *ActivationCodeCreate
	}

	// ActivationCodeUpsert is the "OnConflict" setter.
	ActivationCodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetCode sets the "code" field.
func (u *ActivationCodeUpsert) SetCode(v string) *ActivationCodeUpsert {
	u.Set(activationcode.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ActivationCodeUpsert) UpdateCode() *ActivationCodeUpsert {
	u.SetExcluded(activationcode.FieldCode)
	return u
}

// SetAmount sets the "amount" field.
func (u *ActivationCodeUpsert) SetAmount(v float64) *ActivationCodeUpsert {
	u.Set(activationcode.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ActivationCodeUpsert) UpdateAmount() *ActivationCodeUpsert {
	u.SetExcluded(activationcode.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *ActivationCodeUpsert) AddAmount(v float64) *ActivationCodeUpsert {
	u.Add(activationcode.FieldAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *ActivationCodeUpsert) SetStatus(v string) *ActivationCodeUpsert {
	u.Set(activationcode.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ActivationCodeUpsert) UpdateStatus() *ActivationCodeUpsert {
	u.SetExcluded(activationcode.FieldStatus)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *ActivationCodeUpsert) SetStartsAt(v time.Time) *ActivationCodeUpsert {
	u.Set(activationcode.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *ActivationCodeUpsert) UpdateStartsAt() *ActivationCodeUpsert {
	u.SetExcluded(activationcode.FieldStartsAt)
	return u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *ActivationCodeUpsert) ClearStartsAt() *ActivationCodeUpsert {
	u.SetNull(activationcode.FieldStartsAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *ActivationCodeUpsert) SetExpiresAt(v time.Time) *ActivationCodeUpsert {
	u.Set(activationcode.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ActivationCodeUpsert) UpdateExpiresAt() *ActivationCodeUpsert {
	u.SetExcluded(activationcode.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ActivationCodeUpsert) ClearExpiresAt() *ActivationCodeUpsert {
	u.SetNull(activationcode.FieldExpiresAt)
	return u
}

// SetUsedBy sets the "used_by" field.
func (u *ActivationCodeUpsert) SetUsedBy(v int64) *ActivationCodeUpsert {
	u.Set(activationcode.FieldUsedBy, v)
	return u
}

// UpdateUsedBy sets the "used_by" field to the value that was provided on create.
func (u *ActivationCodeUpsert) UpdateUsedBy() *ActivationCodeUpsert {
	u.SetExcluded(activationcode.FieldUsedBy)
	return u
}

// ClearUsedBy clears the value of the "used_by" field.
func (u *ActivationCodeUpsert) ClearUsedBy() *ActivationCodeUpsert {
	u.SetNull(activationcode.FieldUsedBy)
	return u
}

// SetUsedAt sets the "used_at" field.
func (u *ActivationCodeUpsert) SetUsedAt(v time.Time) *ActivationCodeUpsert {
	u.Set(activationcode.FieldUsedAt, v)
	return u
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *ActivationCodeUpsert) UpdateUsedAt() *ActivationCodeUpsert {
	u.SetExcluded(activationcode.FieldUsedAt)
	return u
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *ActivationCodeUpsert) ClearUsedAt() *ActivationCodeUpsert {
	u.SetNull(activationcode.FieldUsedAt)
	return u
}

// SetNotes sets the "notes" field.
func (u *ActivationCodeUpsert) SetNotes(v string) *ActivationCodeUpsert {
	u.Set(activationcode.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ActivationCodeUpsert) UpdateNotes() *ActivationCodeUpsert {
	u.SetExcluded(activationcode.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *ActivationCodeUpsert) ClearNotes() *ActivationCodeUpsert {
	u.SetNull(activationcode.FieldNotes)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ActivationCodeUpsert) SetUpdatedAt(v time.Time) *ActivationCodeUpsert {
	u.Set(activationcode.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ActivationCodeUpsert) UpdateUpdatedAt() *ActivationCodeUpsert {
	u.SetExcluded(activationcode.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ActivationCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ActivationCodeUpsertOne) UpdateNewValues() *ActivationCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(activationcode.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ActivationCode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ActivationCodeUpsertOne) Ignore() *ActivationCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ActivationCodeUpsertOne) DoNothing() *ActivationCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ActivationCodeCreate.OnConflict
// documentation for more info.
func (u *ActivationCodeUpsertOne) Update(set func(*ActivationCodeUpsert)) *ActivationCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ActivationCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *ActivationCodeUpsertOne) SetCode(v string) *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ActivationCodeUpsertOne) UpdateCode() *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateCode()
	})
}

// SetAmount sets the "amount" field.
func (u *ActivationCodeUpsertOne) SetAmount(v float64) *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ActivationCodeUpsertOne) AddAmount(v float64) *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ActivationCodeUpsertOne) UpdateAmount() *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *ActivationCodeUpsertOne) SetStatus(v string) *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ActivationCodeUpsertOne) UpdateStatus() *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateStatus()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *ActivationCodeUpsertOne) SetStartsAt(v time.Time) *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *ActivationCodeUpsertOne) UpdateStartsAt() *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateStartsAt()
	})
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *ActivationCodeUpsertOne) ClearStartsAt() *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.ClearStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ActivationCodeUpsertOne) SetExpiresAt(v time.Time) *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ActivationCodeUpsertOne) UpdateExpiresAt() *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ActivationCodeUpsertOne) ClearExpiresAt() *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.ClearExpiresAt()
	})
}

// SetUsedBy sets the "used_by" field.
func (u *ActivationCodeUpsertOne) SetUsedBy(v int64) *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetUsedBy(v)
	})
}

// UpdateUsedBy sets the "used_by" field to the value that was provided on create.
func (u *ActivationCodeUpsertOne) UpdateUsedBy() *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateUsedBy()
	})
}

// ClearUsedBy clears the value of the "used_by" field.
func (u *ActivationCodeUpsertOne) ClearUsedBy() *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.ClearUsedBy()
	})
}

// SetUsedAt sets the "used_at" field.
func (u *ActivationCodeUpsertOne) SetUsedAt(v time.Time) *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *ActivationCodeUpsertOne) UpdateUsedAt() *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateUsedAt()
	})
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *ActivationCodeUpsertOne) ClearUsedAt() *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.ClearUsedAt()
	})
}

// SetNotes sets the "notes" field.
func (u *ActivationCodeUpsertOne) SetNotes(v string) *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ActivationCodeUpsertOne) UpdateNotes() *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *ActivationCodeUpsertOne) ClearNotes() *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ActivationCodeUpsertOne) SetUpdatedAt(v time.Time) *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ActivationCodeUpsertOne) UpdateUpdatedAt() *ActivationCodeUpsertOne {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ActivationCodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ActivationCodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ActivationCodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ActivationCodeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ActivationCodeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ActivationCodeCreateBulk is the builder for creating many ActivationCode entities in bulk.
type ActivationCodeCreateBulk struct {
	config
	err      error
	builders []*ActivationCodeCreate
	conflict []sql.ConflictOption
}

// Save creates the ActivationCode entities in the database.
func (_c *ActivationCodeCreateBulk) Save(ctx context.Context) ([]*ActivationCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ActivationCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActivationCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ActivationCodeCreateBulk) SaveX(ctx context.Context) []*ActivationCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActivationCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActivationCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ActivationCode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ActivationCodeUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *ActivationCodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *ActivationCodeUpsertBulk {
	_c.conflict = opts
	return &ActivationCodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ActivationCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ActivationCodeCreateBulk) OnConflictColumns(columns ...string) *ActivationCodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ActivationCodeUpsertBulk{
		create: _c,
	}
}

// ActivationCodeUpsertBulk is the builder for "upsert"-ing
// a bulk of ActivationCode nodes.
type ActivationCodeUpsertBulk struct {
	create *ActivationCodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ActivationCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ActivationCodeUpsertBulk) UpdateNewValues() *ActivationCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(activationcode.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ActivationCode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ActivationCodeUpsertBulk) Ignore() *ActivationCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ActivationCodeUpsertBulk) DoNothing() *ActivationCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ActivationCodeCreateBulk.OnConflict
// documentation for more info.
func (u *ActivationCodeUpsertBulk) Update(set func(*ActivationCodeUpsert)) *ActivationCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ActivationCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *ActivationCodeUpsertBulk) SetCode(v string) *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ActivationCodeUpsertBulk) UpdateCode() *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateCode()
	})
}

// SetAmount sets the "amount" field.
func (u *ActivationCodeUpsertBulk) SetAmount(v float64) *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ActivationCodeUpsertBulk) AddAmount(v float64) *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ActivationCodeUpsertBulk) UpdateAmount() *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *ActivationCodeUpsertBulk) SetStatus(v string) *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ActivationCodeUpsertBulk) UpdateStatus() *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateStatus()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *ActivationCodeUpsertBulk) SetStartsAt(v time.Time) *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *ActivationCodeUpsertBulk) UpdateStartsAt() *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateStartsAt()
	})
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *ActivationCodeUpsertBulk) ClearStartsAt() *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.ClearStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ActivationCodeUpsertBulk) SetExpiresAt(v time.Time) *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ActivationCodeUpsertBulk) UpdateExpiresAt() *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ActivationCodeUpsertBulk) ClearExpiresAt() *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.ClearExpiresAt()
	})
}

// SetUsedBy sets the "used_by" field.
func (u *ActivationCodeUpsertBulk) SetUsedBy(v int64) *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetUsedBy(v)
	})
}

// UpdateUsedBy sets the "used_by" field to the value that was provided on create.
func (u *ActivationCodeUpsertBulk) UpdateUsedBy() *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateUsedBy()
	})
}

// ClearUsedBy clears the value of the "used_by" field.
func (u *ActivationCodeUpsertBulk) ClearUsedBy() *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.ClearUsedBy()
	})
}

// SetUsedAt sets the "used_at" field.
func (u *ActivationCodeUpsertBulk) SetUsedAt(v time.Time) *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *ActivationCodeUpsertBulk) UpdateUsedAt() *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateUsedAt()
	})
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *ActivationCodeUpsertBulk) ClearUsedAt() *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.ClearUsedAt()
	})
}

// SetNotes sets the "notes" field.
func (u *ActivationCodeUpsertBulk) SetNotes(v string) *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ActivationCodeUpsertBulk) UpdateNotes() *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *ActivationCodeUpsertBulk) ClearNotes() *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ActivationCodeUpsertBulk) SetUpdatedAt(v time.Time) *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ActivationCodeUpsertBulk) UpdateUpdatedAt() *ActivationCodeUpsertBulk {
	return u.Update(func(s *ActivationCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ActivationCodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ActivationCodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ActivationCodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ActivationCodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
