// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/uzapi/ent/user"
	"github.com/uzapi/ent/userloginip"
)

// UserLoginIPCreate is the builder for creating a UserLoginIP entity.
type UserLoginIPCreate struct {
	config
	mutation *UserLoginIPMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserLoginIPCreate) SetUserID(v int64) *UserLoginIPCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetIP sets the "ip" field.
func (_c *UserLoginIPCreate) SetIP(v string) *UserLoginIPCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserLoginIPCreate) SetCreatedAt(v time.Time) *UserLoginIPCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserLoginIPCreate) SetNillableCreatedAt(v *time.Time) *UserLoginIPCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *UserLoginIPCreate) SetLastSeenAt(v time.Time) *UserLoginIPCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *UserLoginIPCreate) SetNillableLastSeenAt(v *time.Time) *UserLoginIPCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserLoginIPCreate) SetUser(v *User) *UserLoginIPCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserLoginIPMutation object of the builder.
func (_c *UserLoginIPCreate) Mutation() *UserLoginIPMutation {
	return _c.mutation
}

// Save creates the UserLoginIP in the database.
func (_c *UserLoginIPCreate) Save(ctx context.Context) (*UserLoginIP, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserLoginIPCreate) SaveX(ctx context.Context) *UserLoginIP {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserLoginIPCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserLoginIPCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserLoginIPCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userloginip.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		v := userloginip.DefaultLastSeenAt()
		_c.mutation.SetLastSeenAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserLoginIPCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserLoginIP.user_id"`)}
	}
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "UserLoginIP.ip"`)}
	}
	if v, ok := _c.mutation.IP(); ok {
		if err := userloginip.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "UserLoginIP.ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserLoginIP.created_at"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "UserLoginIP.last_seen_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserLoginIP.user"`)}
	}
	return nil
}

func (_c *UserLoginIPCreate) sqlSave(ctx context.Context) (*UserLoginIP, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserLoginIPCreate) createSpec() (*UserLoginIP, *sqlgraph.CreateSpec) {
	var (
		_node = &UserLoginIP{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userloginip.Table, sqlgraph.NewFieldSpec(userloginip.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(userloginip.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userloginip.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(userloginip.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userloginip.UserTable,
			Columns: []string{userloginip.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserLoginIP.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserLoginIPUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserLoginIPCreate) OnConflict(opts ...sql.ConflictOption) *UserLoginIPUpsertOne {
	_c.conflict = opts
	return &UserLoginIPUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserLoginIP.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserLoginIPCreate) OnConflictColumns(columns ...string) *UserLoginIPUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserLoginIPUpsertOne{
		create: _c,
	}
}

type (
	// UserLoginIPUpsertOne is the builder for "upsert"-ing
	//  one UserLoginIP node.
	UserLoginIPUpsertOne struct {
		create *UserLoginIPCreate
	}

	// UserLoginIPUpsert is the "OnConflict" setter.
	UserLoginIPUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserLoginIPUpsert) SetUserID(v int64) *UserLoginIPUpsert {
	u.Set(userloginip.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserLoginIPUpsert) UpdateUserID() *UserLoginIPUpsert {
	u.SetExcluded(userloginip.FieldUserID)
	return u
}

// SetIP sets the "ip" field.
func (u *UserLoginIPUpsert) SetIP(v string) *UserLoginIPUpsert {
	u.Set(userloginip.FieldIP, v)
	return u
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *UserLoginIPUpsert) UpdateIP() *UserLoginIPUpsert {
	u.SetExcluded(userloginip.FieldIP)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *UserLoginIPUpsert) SetLastSeenAt(v time.Time) *UserLoginIPUpsert {
	u.Set(userloginip.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *UserLoginIPUpsert) UpdateLastSeenAt() *UserLoginIPUpsert {
	u.SetExcluded(userloginip.FieldLastSeenAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserLoginIP.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserLoginIPUpsertOne) UpdateNewValues() *UserLoginIPUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userloginip.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserLoginIP.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserLoginIPUpsertOne) Ignore() *UserLoginIPUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserLoginIPUpsertOne) DoNothing() *UserLoginIPUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserLoginIPCreate.OnConflict
// documentation for more info.
func (u *UserLoginIPUpsertOne) Update(set func(*UserLoginIPUpsert)) *UserLoginIPUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserLoginIPUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserLoginIPUpsertOne) SetUserID(v int64) *UserLoginIPUpsertOne {
	return u.Update(func(s *UserLoginIPUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserLoginIPUpsertOne) UpdateUserID() *UserLoginIPUpsertOne {
	return u.Update(func(s *UserLoginIPUpsert) {
		s.UpdateUserID()
	})
}

// SetIP sets the "ip" field.
func (u *UserLoginIPUpsertOne) SetIP(v string) *UserLoginIPUpsertOne {
	return u.Update(func(s *UserLoginIPUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *UserLoginIPUpsertOne) UpdateIP() *UserLoginIPUpsertOne {
	return u.Update(func(s *UserLoginIPUpsert) {
		s.UpdateIP()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *UserLoginIPUpsertOne) SetLastSeenAt(v time.Time) *UserLoginIPUpsertOne {
	return u.Update(func(s *UserLoginIPUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *UserLoginIPUpsertOne) UpdateLastSeenAt() *UserLoginIPUpsertOne {
	return u.Update(func(s *UserLoginIPUpsert) {
		s.UpdateLastSeenAt()
	})
}

// Exec executes the query.
func (u *UserLoginIPUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserLoginIPCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserLoginIPUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserLoginIPUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserLoginIPUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserLoginIPCreateBulk is the builder for creating many UserLoginIP entities in bulk.
type UserLoginIPCreateBulk struct {
	config
	err      error
	builders []*UserLoginIPCreate
	conflict []sql.ConflictOption
}

// Save creates the UserLoginIP entities in the database.
func (_c *UserLoginIPCreateBulk) Save(ctx context.Context) ([]*UserLoginIP, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserLoginIP, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserLoginIPMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserLoginIPCreateBulk) SaveX(ctx context.Context) []*UserLoginIP {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserLoginIPCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserLoginIPCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserLoginIP.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserLoginIPUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserLoginIPCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserLoginIPUpsertBulk {
	_c.conflict = opts
	return &UserLoginIPUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserLoginIP.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserLoginIPCreateBulk) OnConflictColumns(columns ...string) *UserLoginIPUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserLoginIPUpsertBulk{
		create: _c,
	}
}

// UserLoginIPUpsertBulk is the builder for "upsert"-ing
// a bulk of UserLoginIP nodes.
type UserLoginIPUpsertBulk struct {
	create *UserLoginIPCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserLoginIP.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserLoginIPUpsertBulk) UpdateNewValues() *UserLoginIPUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userloginip.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserLoginIP.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserLoginIPUpsertBulk) Ignore() *UserLoginIPUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserLoginIPUpsertBulk) DoNothing() *UserLoginIPUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserLoginIPCreateBulk.OnConflict
// documentation for more info.
func (u *UserLoginIPUpsertBulk) Update(set func(*UserLoginIPUpsert)) *UserLoginIPUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserLoginIPUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserLoginIPUpsertBulk) SetUserID(v int64) *UserLoginIPUpsertBulk {
	return u.Update(func(s *UserLoginIPUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserLoginIPUpsertBulk) UpdateUserID() *UserLoginIPUpsertBulk {
	return u.Update(func(s *UserLoginIPUpsert) {
		s.UpdateUserID()
	})
}

// SetIP sets the "ip" field.
func (u *UserLoginIPUpsertBulk) SetIP(v string) *UserLoginIPUpsertBulk {
	return u.Update(func(s *UserLoginIPUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *UserLoginIPUpsertBulk) UpdateIP() *UserLoginIPUpsertBulk {
	return u.Update(func(s *UserLoginIPUpsert) {
		s.UpdateIP()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *UserLoginIPUpsertBulk) SetLastSeenAt(v time.Time) *UserLoginIPUpsertBulk {
	return u.Update(func(s *UserLoginIPUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *UserLoginIPUpsertBulk) UpdateLastSeenAt() *UserLoginIPUpsertBulk {
	return u.Update(func(s *UserLoginIPUpsert) {
		s.UpdateLastSeenAt()
	})
}

// Exec executes the query.
func (u *UserLoginIPUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserLoginIPCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserLoginIPCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserLoginIPUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
