// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/uzapi/ent/user"
	"github.com/uzapi/ent/userloginip"
)

// UserLoginIP is the model entity for the UserLoginIP schema.
type UserLoginIP struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 用户 ID
	UserID int64 `json:"user_id,omitempty"`
	// 客户端 IP（IPv4/IPv6）
	IP string `json:"ip,omitempty"`
	// 首次从该 IP 登录的时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 最近一次从该 IP 登录的时间
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserLoginIPQuery when eager-loading is set.
	Edges        UserLoginIPEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserLoginIPEdges holds the relations/edges for other nodes in the graph.
type UserLoginIPEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserLoginIPEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserLoginIP) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userloginip.FieldID, userloginip.FieldUserID:
			values[i] = new(sql.NullInt64)
		case userloginip.FieldIP:
			values[i] = new(sql.NullString)
		case userloginip.FieldCreatedAt, userloginip.FieldLastSeenAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserLoginIP fields.
func (_m *UserLoginIP) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userloginip.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case userloginip.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case userloginip.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		case userloginip.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userloginip.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserLoginIP.
// This includes values selected through modifiers, order, etc.
func (_m *UserLoginIP) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserLoginIP entity.
func (_m *UserLoginIP) QueryUser() *UserQuery {
	return NewUserLoginIPClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserLoginIP.
// Note that you need to call UserLoginIP.Unwrap() before calling this method if this UserLoginIP
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserLoginIP) Update() *UserLoginIPUpdateOne {
	return NewUserLoginIPClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserLoginIP entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserLoginIP) Unwrap() *UserLoginIP {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserLoginIP is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserLoginIP) String() string {
	var builder strings.Builder
	builder.WriteString("UserLoginIP(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserLoginIPs is a parsable slice of UserLoginIP.
type UserLoginIPs []*UserLoginIP
