// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/uzapi/ent/predicate"
	"github.com/uzapi/ent/userloginip"
)

// UserLoginIPDelete is the builder for deleting a UserLoginIP entity.
type UserLoginIPDelete struct {
	config
	hooks    []Hook
	mutation *UserLoginIPMutation
}

// Where appends a list predicates to the UserLoginIPDelete builder.
func (_d *UserLoginIPDelete) Where(ps ...predicate.UserLoginIP) *UserLoginIPDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserLoginIPDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserLoginIPDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserLoginIPDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userloginip.Table, sqlgraph.NewFieldSpec(userloginip.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserLoginIPDeleteOne is the builder for deleting a single UserLoginIP entity.
type UserLoginIPDeleteOne struct {
	_d *UserLoginIPDelete
}

// Where appends a list predicates to the UserLoginIPDelete builder.
func (_d *UserLoginIPDeleteOne) Where(ps ...predicate.UserLoginIP) *UserLoginIPDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserLoginIPDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userloginip.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserLoginIPDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
