// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/uzapi/ent/predicate"
	"github.com/uzapi/ent/user"
	"github.com/uzapi/ent/userloginip"
)

// UserLoginIPUpdate is the builder for updating UserLoginIP entities.
type UserLoginIPUpdate struct {
	config
	hooks    []Hook
	mutation *UserLoginIPMutation
}

// Where appends a list predicates to the UserLoginIPUpdate builder.
func (_u *UserLoginIPUpdate) Where(ps ...predicate.UserLoginIP) *UserLoginIPUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserLoginIPUpdate) SetUserID(v int64) *UserLoginIPUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserLoginIPUpdate) SetNillableUserID(v *int64) *UserLoginIPUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *UserLoginIPUpdate) SetIP(v string) *UserLoginIPUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *UserLoginIPUpdate) SetNillableIP(v *string) *UserLoginIPUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *UserLoginIPUpdate) SetLastSeenAt(v time.Time) *UserLoginIPUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserLoginIPUpdate) SetUser(v *User) *UserLoginIPUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserLoginIPMutation object of the builder.
func (_u *UserLoginIPUpdate) Mutation() *UserLoginIPMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserLoginIPUpdate) ClearUser() *UserLoginIPUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserLoginIPUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserLoginIPUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserLoginIPUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserLoginIPUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserLoginIPUpdate) defaults() {
	if _, ok := _u.mutation.LastSeenAt(); !ok {
		v := userloginip.UpdateDefaultLastSeenAt()
		_u.mutation.SetLastSeenAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserLoginIPUpdate) check() error {
	if v, ok := _u.mutation.IP(); ok {
		if err := userloginip.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "UserLoginIP.ip": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserLoginIP.user"`)
	}
	return nil
}

func (_u *UserLoginIPUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userloginip.Table, userloginip.Columns, sqlgraph.NewFieldSpec(userloginip.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(userloginip.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(userloginip.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userloginip.UserTable,
			Columns: []string{userloginip.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userloginip.UserTable,
			Columns: []string{userloginip.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userloginip.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserLoginIPUpdateOne is the builder for updating a single UserLoginIP entity.
type UserLoginIPUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserLoginIPMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserLoginIPUpdateOne) SetUserID(v int64) *UserLoginIPUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserLoginIPUpdateOne) SetNillableUserID(v *int64) *UserLoginIPUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *UserLoginIPUpdateOne) SetIP(v string) *UserLoginIPUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *UserLoginIPUpdateOne) SetNillableIP(v *string) *UserLoginIPUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *UserLoginIPUpdateOne) SetLastSeenAt(v time.Time) *UserLoginIPUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserLoginIPUpdateOne) SetUser(v *User) *UserLoginIPUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserLoginIPMutation object of the builder.
func (_u *UserLoginIPUpdateOne) Mutation() *UserLoginIPMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserLoginIPUpdateOne) ClearUser() *UserLoginIPUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserLoginIPUpdate builder.
func (_u *UserLoginIPUpdateOne) Where(ps ...predicate.UserLoginIP) *UserLoginIPUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserLoginIPUpdateOne) Select(field string, fields ...string) *UserLoginIPUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserLoginIP entity.
func (_u *UserLoginIPUpdateOne) Save(ctx context.Context) (*UserLoginIP, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserLoginIPUpdateOne) SaveX(ctx context.Context) *UserLoginIP {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserLoginIPUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserLoginIPUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserLoginIPUpdateOne) defaults() {
	if _, ok := _u.mutation.LastSeenAt(); !ok {
		v := userloginip.UpdateDefaultLastSeenAt()
		_u.mutation.SetLastSeenAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserLoginIPUpdateOne) check() error {
	if v, ok := _u.mutation.IP(); ok {
		if err := userloginip.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "UserLoginIP.ip": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserLoginIP.user"`)
	}
	return nil
}

func (_u *UserLoginIPUpdateOne) sqlSave(ctx context.Context) (_node *UserLoginIP, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userloginip.Table, userloginip.Columns, sqlgraph.NewFieldSpec(userloginip.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserLoginIP.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userloginip.FieldID)
		for _, f := range fields {
			if !userloginip.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userloginip.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(userloginip.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(userloginip.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userloginip.UserTable,
			Columns: []string{userloginip.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userloginip.UserTable,
			Columns: []string{userloginip.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserLoginIP{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userloginip.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
